missing_trailer:
  target: validation
  outputs:
    validation:
      type: bigquery
      method: oauth
      project: ray-project-500821
      dataset: dbt_validation
      location: US
      threads: 4
